apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-trial-templates
  namespace: kubeflow
  labels:
    katib.kubeflow.org/component: trial-templates
data:
  xgboostTemplate: |-
    apiVersion: batch/v1
    kind: Job
    spec:
      template:
        metadata:
          annotations:
            "sidecar.istio.io/inject": "false"
        spec:
          containers:
            - name: training-container
              image: docker.io/killer66562/xgboost-trainer:latest
              command:
                - "python3"
                - "/opt/xgboost/train.py"
                - "--lr=${trialParameters.learningRate}"
                - "--ne=5000"
                - "--rs=42"
                - "--esp=1000"
                - "--booster=gbtree"
                - "--device=cuda"
                - "--x_train_path=datasets/x_train.csv"
                - "--x_test_path=datasets/x_test.csv"
                - "--y_train_path=datasets/y_train.csv"
                - "--y_test_path=datasets/y_test.csv"
                - "--save_model=False"
                - "--model_folder_path=models"
          restartPolicy: Never
  rfcTemplate: |-
    apiVersion: batch/v1
    kind: Job
    spec:
      template:
        metadata:
          annotations:
            "sidecar.istio.io/inject": "false"
        spec:
          containers:
            - name: training-container
              image: docker.io/killer66562/rfc-trainer:latest
              command:
                - "python3"
                - "/opt/rfc/train.py"
                - "--ne=5000"
                - "--rs=42"
                - "--mss=${trialParameters.minSamplesSplit}"
                - "--msl=${trialParameters.minSamplesLeaf}"
                - "--ccp_a=${trialParameters.ccpAlpha}"
                - "--x_train_path=datasets/x_train.csv"
                - "--x_test_path=datasets/x_test.csv"
                - "--y_train_path=datasets/y_train.csv"
                - "--y_test_path=datasets/y_test.csv"
                - "--save_model=False"
                - "--model_folder_path=models"
          restartPolicy: Never
  xgboostHeartDiseaseTemplate: |-
    apiVersion: batch/v1
    kind: Job
    spec:
      template:
        metadata:
          annotations:
            "sidecar.istio.io/inject": "false"
        spec:
          containers:
            - name: training-container
              image: docker.io/killer66562/xgboost-trainer-heart-disease:latest
              command:
                - "python3"
                - "/opt/xgboost/train.py"
                - "--lr=${trialParameters.learningRate}"
                - "--ne=5000"
                - "--rs=42"
                - "--esp=1000"
                - "--booster=gbtree"
                - "--device=cuda"
                - "--x_train_path=datasets/x_train.csv"
                - "--x_test_path=datasets/x_test.csv"
                - "--y_train_path=datasets/y_train.csv"
                - "--y_test_path=datasets/y_test.csv"
                - "--save_model=False"
                - "--model_folder_path=models"
          restartPolicy: Never
